#!/usr/bin/env python3
"""
Write the real Photo Library's filenames into real-photos.names.js.

real-photos.html needs the folder's contents to drive itself, and there is no
directory listing over HTTP. So the names are baked into a script the page
loads before it runs.

Run it after adding or removing photos:

  python3 test/list-photos.py

The folder is the host's own, so nothing here is asserted about it: only the
filenames are copied out.
"""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FOLDER = os.path.join(ROOT, 'Photo library')
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'real-photos.names.js')

# What library.js will import: the same extensions its IMAGE_RE accepts.
IMAGE_EXT = ('.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp', '.avif')


def main():
    if not os.path.isdir(FOLDER):
        raise SystemExit('no folder at %s' % FOLDER)

    names = sorted(
        n for n in os.listdir(FOLDER)
        if os.path.isfile(os.path.join(FOLDER, n))
        and n.lower().endswith(IMAGE_EXT)
    )

    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write('/* Generated by test/list-photos.py -- do not edit. */\n')
        fh.write('window.PHOTO_NAMES = ' + json.dumps(names, ensure_ascii=False) + ';\n')

    print('%d photos from %s' % (len(names), os.path.relpath(FOLDER, ROOT)))
    for n in names:
        print('  ' + n)


if __name__ == '__main__':
    main()
